### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by ghost** [hackintosh-club/MAG-B660M-MORTAR-WIFI-DDR4-OpenCore#11]
hi, can you tell me what works, what not?

- sleep
- shutdown
- universal clipboard (copy/paste)
- Airdrop
- is WiFi reliable?
- Wifi speed over 5G
- Handoff
- USB3

or did you maybe replace the Wifi/Bluetooth card with a second-hand broadcom?

thanks!

**Comment by WuLongMiTaoLaiYiDa** [comment]
if u want to use universal clipboard,Airdrop,Handoff   , u need  to replace the wireless  card like BCM94360CS2 or BCM94360CD.  sleep  shutdown  USB3 all functions  works well

**Comment by ghost** [comment]
thank you!

**Comment by WuLongMiTaoLaiYiDa** [comment]
> thank you!

Have fun with Hackintosh
