### ISSUE TITLE
Sleep is not workable

### ISSUE THREAD

**Issue by Goooler** [hackintosh-club/MAG-B660M-MORTAR-WIFI-DDR4-OpenCore#3]
When I'm trying to wake up the machine, it will reboot automatically.

**Comment by Goooler** [comment]
Seems it's related to the latest BIOS (7D42v1B), can't wake up on Windows 11 too.

**Comment by rhwsoft** [comment]
不是这个原因，win11下睡眠后能点亮。

**Comment by Goooler** [comment]
我也发现了，好像是和我的显卡有关，现在关闭

**Comment by rhwsoft** [comment]
关闭核显是必须的

**Comment by RyotaMono** [comment]
> 我也发现了，好像是和我的显卡有关，现在关闭

 很抱歉重开 Issue，请问睡眠后无法点亮的问题解决了嘛? 尝试在 Device Properties 里面加入disable-gpu 核显/Nvidia 独显，依然点不亮..
