### ISSUE TITLE
睡眠后点不亮

### ISSUE THREAD

**Issue by rhwsoft** [hackintosh-club/MAG-B660M-MORTAR-WIFI-DDR4-OpenCore#8]
睡眠后，屏幕黑屏，无法点亮

**Comment by Goooler** [comment]
Duplicate of #3

**Comment by Goooler** [comment]
你在 Windows 下面试过睡眠么，我现在的状况是 Mac 和 Win 都是睡了之后无法用鼠标唤醒，会自动重启。你也是这样吗？

**Comment by rhwsoft** [comment]
> 你在 Windows 下面试过睡眠么，我现在的状况是 Mac 和 Win 都是睡了之后无法用鼠标唤醒，会自动重启。你也是这样吗？
试过了，win11下面没问题，我现在找到一个睡眠可以唤醒的efi。
